config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :casefiles
  get 'hello_world/index'
  root 'hello_world#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/casefile.rb
class Casefile < ApplicationRecord
  def self.search(search)
    # where("uid LIKE ?", "%#{search}%")
    where("name LIKE ?", "%#{search}%")
    # where("nature LIKE ?", "%#{search}%")
    # where("offence LIKE ?", "%#{search}%")
    # where("year LIKE ?", "%#{search}%")
    # where("status LIKE ?", "%#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/casefiles_controller.rb
class CasefilesController < ApplicationController
  before_action :set_casefile, only: [:show, :edit, :update, :destroy]

  # GET /casefiles
  # GET /casefiles.json
  def index
    @casefiles = Casefile.all
    if params[:search]
      @casefiles = Casefile.search(params[:search]).order("created_at DESC")
    else
      @casefiles = Casefile.all.order('created_at DESC')
    end
  end

  # GET /casefiles/1
  # GET /casefiles/1.json
  def show
  end

  # GET /casefiles/new
  def new
    @casefile = Casefile.new
  end

  # GET /casefiles/1/edit
  def edit
  end

  # POST /casefiles
  # POST /casefiles.json
  def create
    @casefile = Casefile.new(casefile_params)

    respond_to do |format|
      if @casefile.save
        format.html { redirect_to @casefile, notice: 'Casefile was successfully created.' }
        format.json { render :show, status: :created, location: @casefile }
      else
        format.html { render :new }
        format.json { render json: @casefile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casefiles/1
  # PATCH/PUT /casefiles/1.json
  def update
    respond_to do |format|
      if @casefile.update(casefile_params)
        format.html { redirect_to @casefile, notice: 'Casefile was successfully updated.' }
        format.json { render :show, status: :ok, location: @casefile }
      else
        format.html { render :edit }
        format.json { render json: @casefile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casefiles/1
  # DELETE /casefiles/1.json
  def destroy
    @casefile.destroy
    respond_to do |format|
      format.html { redirect_to casefiles_url, notice: 'Casefile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @casefiles = Casefile.all
    if params[:search]
      @casefiles = Casefile.search(params[:search]).order("created_at DESC")
    else
      @casefiles = Casefile.all.order('created_at DESC')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_casefile
      @casefile = Casefile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def casefile_params
      params.require(:casefile).permit(:uid, :name, :nature, :offence, :year, :status)
    end
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casefiles_helper.rb
module CasefilesHelper
end

app/helpers/hello_world_helper.rb
module HelloWorldHelper
end

app/views/casefiles/_casefile.html.erb
<% @casefiles.each do |casefile| %>
  <tr>
    <td><%= casefile.uid %></td>
    <td><%= casefile.name %></td>
    <td><%= casefile.nature %></td>
    <td><%= casefile.offence %></td>
    <td><%= casefile.year %></td>
    <td><%= casefile.status %></td>
    <td><%= link_to 'Show', casefile %></td>
    <td><%= link_to 'Edit', edit_casefile_path(casefile) %></td>
    <td><%= link_to 'Destroy', casefile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/casefiles/_form.html.erb
<%= form_with(model: casefile, local: true) do |form| %>
  <% if casefile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(casefile.errors.count, "error") %> prohibited this casefile from being saved:</h2>

      <ul>
      <% casefile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uid %>
    <%= form.text_field :uid, id: :casefile_uid %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :casefile_name %>
  </div>

  <div class="field">
    <%= form.label :nature %>
    <%= form.text_field :nature, id: :casefile_nature %>
  </div>

  <div class="field">
    <%= form.label :offence %>
    <%= form.text_field :offence, id: :casefile_offence %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.date_select :year, id: :casefile_year %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :casefile_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/casefiles/edit.html.erb
<h1>Editing Casefile</h1>

<%= render 'form', casefile: @casefile %>

<%= link_to 'Show', @casefile %> |
<%= link_to 'Back', casefiles_path %>

app/views/casefiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Casefiles</h1>

<%= form_tag(casefiles_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Case Files" %>
<%= submit_tag "Search" %>
<% end %>

<% if @casefiles.present? %>
  <table>
  <thead>
    <tr>
      <th>Uid</th>
      <th>Name</th>
      <th>Nature</th>
      <th>Offence</th>
      <th>Year</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @casefiles.each do |casefile| %>
      <tr>
        <td><%= casefile.uid %></td>
        <td><%= casefile.name %></td>
        <td><%= casefile.nature %></td>
        <td><%= casefile.offence %></td>
        <td><%= casefile.year %></td>
        <td><%= casefile.status %></td>
        <td><%= link_to 'Show', casefile %></td>
        <td><%= link_to 'Edit', edit_casefile_path(casefile) %></td>
        <td><%= link_to 'Destroy', casefile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
 </table>
<% else %>
 <p>There are no case files containing the term(s) <%= params[:search] %>.</p>
<% end %>

<br>

<%= link_to 'New Casefile', new_casefile_path %>

app/views/casefiles/new.html.erb
<h1>New Casefile</h1>

<%= render 'form', casefile: @casefile %>

<%= link_to 'Back', casefiles_path %>

app/views/casefiles/search.html.erb
<%= form_tag(casefiles_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Case Files" %>
<%= submit_tag "Search" %>
<% end %>

<% if @casefiles.present? %>
  <%= render @casefiles %>
<% else %>
  <p>There are no case files containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/casefiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>UID:</strong>
  <%= @casefile.uid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @casefile.name %>
</p>

<p>
  <strong>Nature:</strong>
  <%= @casefile.nature %>
</p>

<p>
  <strong>Offence:</strong>
  <%= @casefile.offence %>
</p>

<p>
  <strong>Year:</strong>
  <%= @casefile.year %>
</p>

<p>
  <strong>Status:</strong>
  <%= @casefile.status %>
</p>

<%= link_to 'Edit', edit_casefile_path(@casefile) %> |
<%= link_to 'Back', casefiles_path %>

app/views/hello_world/index.html.erb
<div class="container">
  <section>
    <img alt="Welcome" width="600" height="350" src="/images/intro.jpg" />

    <p class="version">
      <%= link_to 'New Casefile', new_casefile_path %>
      <br />
      <%= link_to 'Show Casefile', '/casefiles/' %>
    </p>

  </section>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags-->
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <title> Shrimadhav U K </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>